### ISSUE TITLE
Issues when upgrading pootle from 2.0.3 to 2.1.0

### ISSUE THREAD

**Issue by transl8bzimport** [translate/pootle#1615]
_Originally posted by cies breijs:_

i also upgraded translate-toolkit to 1.7.1, and django to 1.2.1
the upgrades where performed by simply running "./setup.py install" over the other install.

when running the service like where used to i get:
Starting server, listening on port 8888.
###### ### here i make a GET request on '/', then i see:

2010-08-11 15:44:30,945 INFO Starting Django server, listening on port 8888
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 280, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 674, in **call**
    return self.application(environ, start_response)
  File "/usr/lib/python2.5/site-packages/django/core/handlers/wsgi.py", line 230, in **call**
    self.load_middleware()
  File "/usr/lib/python2.5/site-packages/django/core/handlers/base.py", line 42, in load_middleware
    raise exceptions.ImproperlyConfigured('Error importing middleware %s: "%s"' % (mw_module, e))
ImproperlyConfigured: Error importing middleware pootle_misc.middleware.siteconfig: "cannot import name Language"
[11/Aug/2010 15:44:43] "GET / HTTP/1.1" 500 780

then i try to run pootle from the extracted tar contents... that works.
but when i then copy my dbs/ and po/ dirs into that directory is sais:

Starting server, listening on port 8888.
2010-08-11 16:12:31,984 INFO Starting Django server, listening on port 8888
2010-08-11 16:12:40,109 WARNING Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
2010-08-11 16:12:40,173 INFO Creating missing database tables
Creating table pootle_store_qualitycheck
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 281, in run
    self.finish_response()
  File "/usr/lib/python2.5/site-packages/django/core/servers/basehttp.py", line 320, in finish_response
    for data in self.result:
  File "/usr/lib/python2.5/site-packages/django/http/**init**.py", line 408, in next
    chunk = self._iterator.next()
  File "/home/pootle/Pootle-2.1.0-rc1/local_apps/pootle_misc/dbupdate.py", line 199, in staggered_update
    yield syncdb()
  File "/home/pootle/Pootle-2.1.0-rc1/local_apps/pootle_misc/dbupdate.py", line 80, in syncdb
    call_command('syncdb', interactive=False)
  File "/usr/lib/python2.5/site-packages/django/core/management/__init__.py", line 166, in call_command
    return klass.execute(_args, *_defaults)
  File "/usr/lib/python2.5/site-packages/django/core/management/base.py", line 218, in execute
    output = self.handle(_args, *_options)
  File "/usr/lib/python2.5/site-packages/django/core/management/base.py", line 347, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.5/site-packages/django/core/management/commands/syncdb.py", line 95, in handle_noargs
    cursor.execute(statement)
  File "/usr/lib/python2.5/site-packages/django/db/backends/sqlite3/base.py", line 200, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: database disk image is malformed

we use sqlite for database.
