### ISSUE TITLE
XLIFF doesn't work in Pootle 1.1.0

### ISSUE THREAD

**Issue by sorenroug** [translate/pootle#465]
_Version: 1.1.0_

When creating a project that takes 'xlf' files and uploading the first XLIFF file, the project page stops working with the error message: AttributeError: 'unicode' object has no attribute 'strings'

Pootle logs this trace:

<pre>
---------------
2008-07-11 11:13:27: Traceback (most recent call last):
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/users.py", line 259, in handle
    page = self.getpage(pathwords, session, argdict)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/pootle.py", line 325, in getpage
    return indexpage.ProjectLanguageIndex(self.potree, projectcode, session)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/indexpage.py", line 258, in __init__
    languages = self.getlanguages()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/indexpage.py", line 286, in getlanguages
    languageitems = [self.getlanguageitem(languagecode, languagename) for languagecode, languagename in languages]
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/indexpage.py", line 295, in getlanguageitem
    language = self.potree.getproject(languagecode, self.projectcode)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/potree.py", line 311, in getproject
    self.projectcache[languagecode, projectcode] = projects.TranslationProject(languagecode, projectcode, self)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/projects.py", line 113, in __init__
    self.scanpofiles()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/projects.py", line 458, in scanpofiles
    self.pofiles[pofilename] = pootlefile.pootlefile(self, pofilename)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/pootlefile.py", line 281, in __init__
    self.statistics = statistics.pootlestatistics(self, generatestats)
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/statistics.py", line 56, in __init__
    self.getstats()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/statistics.py", line 74, in getstats
    self.calcstats()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/statistics.py", line 152, in calcstats
    self.basefile.pofreshen()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/pootlefile.py", line 482, in pofreshen
    self.readpofile()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/pootlefile.py", line 468, in readpofile
    self.statistics.classifyunits()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/statistics.py", line 188, in classifyunits
    self.countwords()
  File "/var/local/python245/lib/python2.4/site-packages/Pootle/statistics.py", line 195, in countwords
    self.sourcewordcounts.append([statsdb.wordcount(text) for text in unit.source.strings])
AttributeError: 'unicode' object has no attribute 'strings'
---------------
</pre>

My own preliminary analysis reveals that translate-toolkit-1.1.1 uses a class called 'multistring' to hold source and target for translation-units in PO files. They therefore have an attribute called 'strings', like in 'unit.source.strings'. The XLIFF parser in translate-toolkit uses regular unicode strings for source and target, and it is not possible to count words the same way in XLIFF files.
