### ISSUE TITLE
Pootle 2.5 release

### ISSUE THREAD

**Issue by dwaynebailey** [translate/pootle#2191]
Depends on:
- [x] #1335 [VCS] Enable commit for a complete directory / language / project
- [x] #1625 Warn users about actions that could take long
- [x] #1758 Provide natural names for checks
- [x] #1927 Checking for XHR Server Errors in editor
- [x] #1990 Unfuzzied units in upload don’t change server state
- [x] #2003 download view masks real directory called download
- [x] #2125 Internationalize JavaScript texts
- [x] #2149 Classify pofilter tests in the editor
- [x] translate/translate#2157 Can't commit an unchanged file to git
- [x] #2182 Classify pofilter tests
- [x] #2183 Context information can be confusing
- [x] #2192 Align project and language description's look with overview pages
- [x] #2193 Cancel and save buttons in description update are confusing
- [x] #2195 Translation project description hides inherited descriptions
- [x] #2196 Comments that is too long with no space don't wrap and moves into source text content
- [x] #2198 With no description there is no logical place for the edit icon
- [x] #2201 Generate CSS sprites
- [x] #2211 Revisit source text bug reporting icon placement
- [x] #2212 Permalink to a unit
- [x] #2220 Overview page expanded view stats do not update when drilling down
- [x] #2221 Expanded overview page translation states should not be present if they are zero
- [x] #2223 Overview number columns header must be right aligned
- [x] #2224 Overview page column headers should remember their sort order
- [x] #2226 Add progress bar to overview header
- [x] #2228 Clicking on an overview directory or file should leave you in overview mode
- [x] #2230 Expanded overview table reading issues
- [x] #2232 No indication of items that have suggestions
- [x] #2236 Schema upgrade doesn't complete fully
- [x] #2241 Add tfoot to administration tables
- [x] #2242 Add link to parent directory
- [x] #2246 Reorganize setting files
- [x] translate/translate#2247 Release Translate Toolkit 1.10
- [x] #2251 [DeprecationWarning] The ADMIN_MEDIA_PREFIX setting has been removed; use STATIC_URL instead.
- [x] #2256 No feedback when clicking 'Save changes' in admin/projects.html
- [x] #2257 setup.py not working after code reshuffle
- [x] #2260 Not obvious when work on translation page is complete
- [x] #2261 Add any strange characters in source to special characters
- [x] #2273 Missing file path and names on translate page
- [x] #2276 Overview page summary title shouldn't include language and project codes
- [x] #2285 Upload file, Upload to dropbox destination files should be shortened to prevent confusion.
- [x] #2292 Clickable links all have different underline styling
- [x] #2294 Check that all new Pootle 2.2 strings are localisable
- [x] #2296 Make commenting an explicit action
- [x] #2297 Highlighting of special characters found strings is hard to see
- [x] #2299 Failing to load translate page (tu is undefined)
- [x] #2301 Merge 'Translate' and 'Overview' tabs
- [x] #2302 Removing false positive creates subsequent traceback in get_quality_check_failures
- [x] #2307 Entering a folder with no translations causes backtrace in progressbar.py
- [x] #2323 Unwanted tabs \t added when copying text to be translated
- [x] #2327 Review if jquery.form.js is necessary
- [x] #2332 Remember which page you came from when you login
- [x] #2338 Standard styling for user contributed HTML
- [x] #2343 Returning to the overview page from the translate page should take you back to where you started
- [x] #2362 Files and directories with "0 words needing attention" mask those that do need work
- [x] translate/translate#2368 list.remove(x) error on mozilla.locamotion.org
- [x] #2369 Error when updating database from 2.1.6 to 2.2.0-alpha1a
- [x] #2373 Rewrite term_edit.html template
- [x] #2382 Some includes are not compatible with Django 1.2
- [x] #2396 Submission model definition not compatible with Django 1.2
- [x] #2400 AttributeError: 'tuple' object has no attribute '_meta'
- [x] #2403 Clicking out of a textarea for a fuzzy unit makes it unfuzzy
- [x] #2416 Can't download zip of directory with non-ascii chars
- [x] #2419 Traceback in get_quality_check_failures
- [x] #2424 Opening project descriptions causes screen to jump
- [x] #2425 Clear 'hassuggestion' checks on upgrade
- [x] #2430 Merge about contributors page
- [x] #2434 Missing progressbars on http://localhost:8080/projects/
- [x] #2435 Project and Language pages 'Need Translation' links point back to current page
- [x] #2436 Remember search fields' choice
- [x] #2437 AttributeError: 'NoneType' object has no attribute 'find'
- [x] #2442 Failing checks are rendered above source text
- [x] #2444 Long comments cause TM and comments to appear far down from target text
- [x] #2447 Use a table for rendering the checks
- [x] #2449 Can't compare offset-naive and offset-aware datetimes
- [x] #2483 Enable Wikipedia lookup by default
- [x] #2486 Document all configuration options
- [x] #2489 Correct all reference to localsettings.py in the docs
- [x] #2496 Wrong sort of Needs Translation column in subdirectories
- [x] #2502 Create general navbar
- [x] #2511 Avoid deleting a translation project's directory
- [x] #2516 Language dropdown in administration not sorted with Opera or Chrome
- [x] #2522 Obsolete settings?
- [x] #2523 Replace user.message_set with the messages framework
- [x] #2537 updatedb traceback: "Unknown column 'pootle_app_translationproject.description' in 'field list'"
- [x] #2538 Fuzzy strings from VCS overwrite translated ones
- [x] #2558 [VCS] New files not added properly when initializing language from templates
- [x] #2561 VCS-related links disappear after 'Rescan project files'
- [x] #2562 No way to access online translation when file is 100% translated
- [x] #2566 Create 'pootle' runner script
- [x] #2567 Can't init DB when TIME_ZONE is set to anything other than UTC
- [x] #2568 News emails expose contributors email addresses
- [x] #2569 News post to language project sends to everyone
- [x] translate/translate#2570 Android resources support
- [x] #2572 Setup translations from pootle.locamotion.org
- [x] #2576 Timezone warning: DateTimeField received a naive datetime
- [x] #2577 Error on updating translation from template
- [x] #2584 Inconsistent editor fuzzying behavior
- [x] translate/translate#2587 pot2po on some LibreOffice files leads to fuzzies where msgmerge creates none
- [x] #2605 Update from VCS deletes translations
- [x] #2609 Permission Denied page throws Django.utils error
- [x] #2610 Include LICENSE file in Pootle's source code
- [x] #2615 New description is appended instead of updating the current text
- [x] #2616 Can't do single file translation
- [x] #2617 Missing username in user registration
- [x] #2620 Can't enter a new fuzzy translation
- [x] #2621 Too many fuzzy units after updating from templates
- [x] #2637 Conflicting shortcut key on translate page
- [x] #2644 Incorrect redirect logic after login when Pootle root url is some directory, not "/"
- [x] #2659 "&amp;" inside URL is rendered in Pootle UI as "&", which impacts translation
- [x] #2660 Localisation incorrect on login page
- [x] #2661 Review RTL interface for Pootle 2.5
- [x] #2663 Disabled next/previous buttons have markup in tooltip
- [x] #2668 Review variable substitution for strings
- [x] #2674 Context row actions are not localisable
- [x] #2696 Update Pootle Pip install
- [x] #2697 Assets are missing in the sdist build
- [x] #2726 range() integer end argument expected, got list.
- [x] #2734 Get Pootle translations and update to latest templates
- [x] #2735 Project page translations bleeding across languages
- [x] #2746 Create RC for Pootle 2.5.0
- [x] #2748 Update INSTALL file to reflect changes in installation process between 2.5.x and previous versions
- [x] #2750 Pootle make mo doesn't work on Python<=2.7
- [x] #2751 Update .travis.yml to get Travis builds working again and to update Django versions
- [x] #2850 Package and release Pootle 2.5.0 final

A gathering place for all bugs that we'd like to fix for a Pootle 2.2 release
