### ISSUE TITLE
Uncaught Error: Cannot find module "lodash/isPlainObject" upon upgrade to 2.7.4

### ISSUE THREAD

**Issue by jason-p-pickering** [translate/pootle#4742]
![image](https://cloud.githubusercontent.com/assets/2968061/15419857/529f40e0-1e69-11e6-8f32-481660fab29d.png)

Getting a JS error after upgrade from 2.7.3 to 2.7.4

Getting the same error with pootle webpack

```
ERROR in ./~/redux/lib/createStore.js
Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in /var/www/pootle/env/lib/python2.7/site-packages/pootle/static/js/node_modules/redux/lib
 @ ./~/redux/lib/createStore.js 7:21-52

ERROR in ./~/redux/lib/combineReducers.js
Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in /var/www/pootle/env/lib/python2.7/site-packages/pootle/static/js/node_modules/redux/lib
 @ ./~/redux/lib/combineReducers.js 8:21-52
```

Any idea what might be the problem?

**Comment by unho** [comment]
Fixed by cb0358357c76.
