### ISSUE TITLE
refresh_stats is broken

### ISSUE THREAD

**Issue by julen** [translate/pootle#3271]
`refresh_stats` is broken because of an API mismatch.

``` python
Traceback (most recent call last):
  File "/var/www/sites/pootle-custom-mlo/env/src/pootle-dev/pootle/apps/pootle_app/management/commands/__init__.py", line 88, in do_translation_project
    self.handle_store(store, **options)
  File "/var/www/sites/pootle-custom-mlo/env/src/pootle-dev/pootle/apps/pootle_app/management/commands/refresh_stats.py", line 90, in handle_store
    store.update_qualitychecks(keep_false_positives=True)
  File "/var/www/sites/pootle-custom-mlo/env/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
TypeError: update_qualitychecks() got an unexpected keyword argument 'keep_false_positives'
```

This is a regression introduced in cf1ce1f6819.
